apiVersion: apps/v1
kind: Deployment
metadata:
  name: dateapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dateapp
  template:
    metadata:
      labels:
        app: dateapp
    spec:
      containers:
      - name: dateapp
        image: yourdockerhub/dateapp
        ports:
        - containerPort: 8080
